/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface KittyInterfaceInterface extends Interface {
  getFunction(nameOrSignature: "getKitty"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getKitty",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getKitty", data: BytesLike): Result;
}

export interface KittyInterface extends BaseContract {
  connect(runner?: ContractRunner | null): KittyInterface;
  waitForDeployment(): Promise<this>;

  interface: KittyInterfaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKitty: TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isGestating: boolean;
        isReady: boolean;
        cooldownIndex: bigint;
        nextActionAt: bigint;
        siringWithId: bigint;
        birthTime: bigint;
        matronId: bigint;
        sireId: bigint;
        generation: bigint;
        genes: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKitty"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isGestating: boolean;
        isReady: boolean;
        cooldownIndex: bigint;
        nextActionAt: bigint;
        siringWithId: bigint;
        birthTime: bigint;
        matronId: bigint;
        sireId: bigint;
        generation: bigint;
        genes: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
