/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { PriceConsumer, PriceConsumerInterface } from "../PriceConsumer";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getDecimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLatestPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "priceFeed",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600180546001600160a01b031916738a753747a1fa494ec906ce90e9f37563a8af630e17905534801561003657600080fd5b50600154600080546001600160a01b0319166001600160a01b039092169190911790556102c8806100686000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063741bef1a146100465780638e15f47314610090578063f0141d84146100a6575b600080fd5b6000546100669073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b6100986100c0565b604051908152602001610087565b6100ae61015f565b60405160ff9091168152602001610087565b60008054604080517ffeaf968c0000000000000000000000000000000000000000000000000000000081529051839273ffffffffffffffffffffffffffffffffffffffff169163feaf968c9160048083019260a09291908290030181865afa158015610130573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101549190610218565b509195945050505050565b60008054604080517f313ce5670000000000000000000000000000000000000000000000000000000081529051839273ffffffffffffffffffffffffffffffffffffffff169163313ce5679160048083019260209291908290030181865afa1580156101cf573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101f39190610268565b92915050565b805169ffffffffffffffffffff8116811461021357600080fd5b919050565b600080600080600060a0868803121561023057600080fd5b610239866101f9565b945060208601519350604086015192506060860151915061025c608087016101f9565b90509295509295909350565b60006020828403121561027a57600080fd5b815160ff8116811461028b57600080fd5b939250505056fea2646970667358221220f3bd0b5aad330930e42a528358dc89ecd4f02955a451c18873137c8c167bc1cf64736f6c63430008120033";

type PriceConsumerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PriceConsumerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PriceConsumer__factory extends ContractFactory {
  constructor(...args: PriceConsumerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PriceConsumer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PriceConsumer__factory {
    return super.connect(runner) as PriceConsumer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PriceConsumerInterface {
    return new Interface(_abi) as PriceConsumerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PriceConsumer {
    return new Contract(address, _abi, runner) as unknown as PriceConsumer;
  }
}
