/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as lib from "./lib";
import type * as zombieHelperSol from "./zombieHelper.sol";
import type * as zombieattackSol from "./zombieattack.sol";
import type * as zombiefactorySol from "./zombiefactory.sol";
import type * as zombiefeedingSol from "./zombiefeeding.sol";
import type * as zombieownershipSol from "./zombieownership.sol";

export type { lib };

export type { zombieHelperSol };

export type { zombieattackSol };

export type { zombiefactorySol };

export type { zombiefeedingSol };

export type { zombieownershipSol };
export type { CryptoZombies } from "./CryptoZombies";
export type { PriceConsumer } from "./PriceConsumer";
export type { Transactions } from "./Transactions";
export * as factories from "./factories";
export { CryptoZombies__factory } from "./factories/CryptoZombies__factory";
export type { AggregatorV3Interface } from "./lib/AggregatorV3Interface";
export { AggregatorV3Interface__factory } from "./factories/lib/AggregatorV3Interface__factory";
export type { ERC721 } from "./lib/erc721.sol/ERC721";
export { ERC721__factory } from "./factories/lib/erc721.sol/ERC721__factory";
export type { KittyInterface } from "./lib/kitty.sol/KittyInterface";
export { KittyInterface__factory } from "./factories/lib/kitty.sol/KittyInterface__factory";
export type { Ownable } from "./lib/ownable.sol/Ownable";
export { Ownable__factory } from "./factories/lib/ownable.sol/Ownable__factory";
export { PriceConsumer__factory } from "./factories/PriceConsumer__factory";
export { Transactions__factory } from "./factories/Transactions__factory";
export type { ZombieAttack } from "./zombieattack.sol/ZombieAttack";
export { ZombieAttack__factory } from "./factories/zombieattack.sol/ZombieAttack__factory";
export type { ZombieFactory } from "./zombiefactory.sol/ZombieFactory";
export { ZombieFactory__factory } from "./factories/zombiefactory.sol/ZombieFactory__factory";
export type { ZombieFeeding } from "./zombiefeeding.sol/ZombieFeeding";
export { ZombieFeeding__factory } from "./factories/zombiefeeding.sol/ZombieFeeding__factory";
export type { ZombieHelper } from "./zombieHelper.sol/ZombieHelper";
export { ZombieHelper__factory } from "./factories/zombieHelper.sol/ZombieHelper__factory";
export type { ZombieOwnership } from "./zombieownership.sol/ZombieOwnership";
export { ZombieOwnership__factory } from "./factories/zombieownership.sol/ZombieOwnership__factory";
