/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721Sol from "./erc721.sol";
export type { erc721Sol };
import type * as kittySol from "./kitty.sol";
export type { kittySol };
import type * as ownableSol from "./ownable.sol";
export type { ownableSol };
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
